name: Golang beta

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.5

      - name: Install beta version
        run: |
          go install golang.org/dl/go1.18beta1@latest
          go1.18beta1 download
          cp $(which go1.18beta1) $(which go)
          go version