name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        type: string
        required: true
      fruit:
        type: choice
        options: [ 'apples', 'oranges' ]
        required: true
      age:
        type: number
      test:
        type: boolean
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
    - name: Fruit preference
      run: echo "You prefer ${{ github.event.inputs.fruit }}"
    - name: Print age
      run: echo "You are ${{ github.event.inputs.age }} old"
    - name: Test
      if: ${{ github.event.inputs.test }}
      run: echo 'This is a test'
